apiVersion: v1
kind: ConfigMap
metadata:
  name: sip-runtime-config
  namespace: sip-system
data:
  SIP_DEPLOYMENT_PROFILE: edge
  SIP_OBJECT_STORE_BACKEND: local
  SIP_REQUIRE_PRIVATE_ENDPOINTS: 'true'
  SIP_PRODUCTION_AUTHORIZED: 'false'
