apiVersion: v1
kind: ConfigMap
metadata:
  name: sip-runtime-config
  namespace: sip-system
data:
  SIP_DEPLOYMENT_PROFILE: aws
  SIP_OBJECT_STORE_BACKEND: s3
  SIP_S3_PREFIX: sip
  AWS_REGION: REPLACE_WITH_TERRAFORM_REGION_OUTPUT
  SIP_S3_REGION: REPLACE_WITH_TERRAFORM_REGION_OUTPUT
  SIP_S3_BUCKET: REPLACE_WITH_TERRAFORM_EVIDENCE_BUCKET_OUTPUT
  SIP_S3_KMS_KEY_ID: REPLACE_WITH_TERRAFORM_PLATFORM_KMS_OUTPUT
  SIP_REQUIRE_PRIVATE_ENDPOINTS: 'true'
