"""Progress 09 deployment profiles and production-shaped infrastructure"""
from alembic import op
import os
import re
import sqlalchemy as sa
revision = '0019_progress09_deployment_profiles'
down_revision = '0018_progress08_observability_cost_support'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoscaling_admissions',
    sa.Column('admission_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('autoscaling_policy_id', sa.String(length=64), nullable=False),
    sa.Column('queue_class', sa.String(length=64), nullable=False),
    sa.Column('capability_profile', sa.String(length=128), nullable=False),
    sa.Column('current_replicas', sa.Integer(), nullable=False),
    sa.Column('requested_replicas', sa.Integer(), nullable=False),
    sa.Column('admitted_replicas', sa.Integer(), nullable=False),
    sa.Column('active_jobs', sa.Integer(), nullable=False),
    sa.Column('estimated_incremental_cost', sa.Float(), nullable=False),
    sa.Column('global_cost_after', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('decision_hash', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('admission_id'),
    sa.UniqueConstraint('decision_hash')
    )
    op.create_index(op.f('ix_autoscaling_admissions_autoscaling_policy_id'), 'autoscaling_admissions', ['autoscaling_policy_id'], unique=False)
    op.create_index(op.f('ix_autoscaling_admissions_capability_profile'), 'autoscaling_admissions', ['capability_profile'], unique=False)
    op.create_index(op.f('ix_autoscaling_admissions_decision'), 'autoscaling_admissions', ['decision'], unique=False)
    op.create_index(op.f('ix_autoscaling_admissions_project_id'), 'autoscaling_admissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_autoscaling_admissions_queue_class'), 'autoscaling_admissions', ['queue_class'], unique=False)
    op.create_index(op.f('ix_autoscaling_admissions_reason_code'), 'autoscaling_admissions', ['reason_code'], unique=False)
    op.create_index(op.f('ix_autoscaling_admissions_tenant_id'), 'autoscaling_admissions', ['tenant_id'], unique=False)
    op.create_table('aws_environment_manifests',
    sa.Column('aws_environment_id', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('account_boundary', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('infrastructure_versions_json', sa.JSON(), nullable=False),
    sa.Column('network_json', sa.JSON(), nullable=False),
    sa.Column('database_json', sa.JSON(), nullable=False),
    sa.Column('object_store_json', sa.JSON(), nullable=False),
    sa.Column('queue_json', sa.JSON(), nullable=False),
    sa.Column('kms_json', sa.JSON(), nullable=False),
    sa.Column('secrets_json', sa.JSON(), nullable=False),
    sa.Column('cdn_json', sa.JSON(), nullable=False),
    sa.Column('gpu_json', sa.JSON(), nullable=False),
    sa.Column('export_replacement_paths_json', sa.JSON(), nullable=False),
    sa.Column('evidence_class', sa.String(length=64), nullable=False),
    sa.Column('production_approved', sa.Boolean(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('aws_environment_id'),
    sa.UniqueConstraint('environment', 'account_boundary', 'region', name='uq_aws_environment_boundary'),
    sa.UniqueConstraint('manifest_hash')
    )
    op.create_index(op.f('ix_aws_environment_manifests_account_boundary'), 'aws_environment_manifests', ['account_boundary'], unique=False)
    op.create_index(op.f('ix_aws_environment_manifests_environment'), 'aws_environment_manifests', ['environment'], unique=False)
    op.create_index(op.f('ix_aws_environment_manifests_region'), 'aws_environment_manifests', ['region'], unique=False)
    op.create_table('cdn_derivative_deliveries',
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('immutable_sha256', sa.String(length=64), nullable=False),
    sa.Column('redaction_profile', sa.String(length=128), nullable=False),
    sa.Column('redaction_hash', sa.String(length=64), nullable=False),
    sa.Column('signed_authorization_required', sa.Boolean(), nullable=False),
    sa.Column('raw_origin', sa.Boolean(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('delivery_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id'),
    sa.UniqueConstraint('delivery_hash'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_cdn_derivative_deliveries_asset_id'), 'cdn_derivative_deliveries', ['asset_id'], unique=False)
    op.create_index(op.f('ix_cdn_derivative_deliveries_project_id'), 'cdn_derivative_deliveries', ['project_id'], unique=False)
    op.create_index(op.f('ix_cdn_derivative_deliveries_state'), 'cdn_derivative_deliveries', ['state'], unique=False)
    op.create_index(op.f('ix_cdn_derivative_deliveries_tenant_id'), 'cdn_derivative_deliveries', ['tenant_id'], unique=False)
    op.create_table('deployment_admissions',
    sa.Column('admission_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('admission_type', sa.String(length=64), nullable=False),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('obligations_json', sa.JSON(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('admission_id'),
    sa.UniqueConstraint('evidence_hash')
    )
    op.create_index(op.f('ix_deployment_admissions_admission_type'), 'deployment_admissions', ['admission_type'], unique=False)
    op.create_index(op.f('ix_deployment_admissions_decision'), 'deployment_admissions', ['decision'], unique=False)
    op.create_index(op.f('ix_deployment_admissions_deployment_profile_id'), 'deployment_admissions', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_deployment_admissions_project_id'), 'deployment_admissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployment_admissions_reason_code'), 'deployment_admissions', ['reason_code'], unique=False)
    op.create_index(op.f('ix_deployment_admissions_region'), 'deployment_admissions', ['region'], unique=False)
    op.create_index(op.f('ix_deployment_admissions_tenant_id'), 'deployment_admissions', ['tenant_id'], unique=False)
    op.create_table('deployment_drift_reports',
    sa.Column('drift_report_id', sa.String(length=64), nullable=False),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('expected_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_hash', sa.String(length=64), nullable=False),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_by', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('drift_report_id'),
    sa.UniqueConstraint('report_hash')
    )
    op.create_index(op.f('ix_deployment_drift_reports_deployment_profile_id'), 'deployment_drift_reports', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_deployment_drift_reports_status'), 'deployment_drift_reports', ['status'], unique=False)
    op.create_table('deployment_profiles',
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('canonical_contracts_json', sa.JSON(), nullable=False),
    sa.Column('canonical_contracts_hash', sa.String(length=64), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('service_images_json', sa.JSON(), nullable=False),
    sa.Column('infrastructure_versions_json', sa.JSON(), nullable=False),
    sa.Column('secret_references_json', sa.JSON(), nullable=False),
    sa.Column('network_policy_json', sa.JSON(), nullable=False),
    sa.Column('resource_limits_json', sa.JSON(), nullable=False),
    sa.Column('supported_regions_json', sa.JSON(), nullable=False),
    sa.Column('degraded_modes_json', sa.JSON(), nullable=False),
    sa.Column('provider_replacements_json', sa.JSON(), nullable=False),
    sa.Column('production_approved', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('profile_hash', sa.String(length=64), nullable=False),
    sa.Column('supersedes_profile_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('deployment_profile_id'),
    sa.UniqueConstraint('name', 'revision', name='uq_deployment_profile_revision'),
    sa.UniqueConstraint('profile_hash')
    )
    op.create_index(op.f('ix_deployment_profiles_canonical_contracts_hash'), 'deployment_profiles', ['canonical_contracts_hash'], unique=False)
    op.create_index(op.f('ix_deployment_profiles_mode'), 'deployment_profiles', ['mode'], unique=False)
    op.create_index(op.f('ix_deployment_profiles_name'), 'deployment_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_deployment_profiles_state'), 'deployment_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_deployment_profiles_supersedes_profile_id'), 'deployment_profiles', ['supersedes_profile_id'], unique=False)
    op.create_table('graceful_shutdown_evidence',
    sa.Column('shutdown_id', sa.String(length=64), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('operation_ids_json', sa.JSON(), nullable=False),
    sa.Column('checkpoint_hashes_json', sa.JSON(), nullable=False),
    sa.Column('queue_before_json', sa.JSON(), nullable=False),
    sa.Column('queue_after_json', sa.JSON(), nullable=False),
    sa.Column('recovery_json', sa.JSON(), nullable=False),
    sa.Column('shutdown_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('recorded_by', sa.String(length=128), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('shutdown_id'),
    sa.UniqueConstraint('shutdown_hash')
    )
    op.create_index(op.f('ix_graceful_shutdown_evidence_deployment_profile_id'), 'graceful_shutdown_evidence', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_graceful_shutdown_evidence_state'), 'graceful_shutdown_evidence', ['state'], unique=False)
    op.create_index(op.f('ix_graceful_shutdown_evidence_worker_id'), 'graceful_shutdown_evidence', ['worker_id'], unique=False)
    op.create_table('local_upgrade_rehearsals',
    sa.Column('rehearsal_id', sa.String(length=64), nullable=False),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('from_release', sa.String(length=128), nullable=False),
    sa.Column('to_release', sa.String(length=128), nullable=False),
    sa.Column('from_schema', sa.String(length=128), nullable=False),
    sa.Column('to_schema', sa.String(length=128), nullable=False),
    sa.Column('pre_export_root', sa.String(length=64), nullable=False),
    sa.Column('post_upgrade_export_root', sa.String(length=64), nullable=False),
    sa.Column('rollback_export_root', sa.String(length=64), nullable=False),
    sa.Column('object_store_root', sa.String(length=64), nullable=False),
    sa.Column('queue_root', sa.String(length=64), nullable=False),
    sa.Column('job_recovery_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('rehearsal_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('rehearsal_id'),
    sa.UniqueConstraint('rehearsal_hash')
    )
    op.create_index(op.f('ix_local_upgrade_rehearsals_deployment_profile_id'), 'local_upgrade_rehearsals', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_local_upgrade_rehearsals_state'), 'local_upgrade_rehearsals', ['state'], unique=False)
    op.create_table('offline_update_packages',
    sa.Column('update_id', sa.String(length=64), nullable=False),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('from_release', sa.String(length=128), nullable=False),
    sa.Column('to_release', sa.String(length=128), nullable=False),
    sa.Column('bundle_hash', sa.String(length=64), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('signing_key_id', sa.String(length=128), nullable=False),
    sa.Column('rollback_bundle_hash', sa.String(length=64), nullable=False),
    sa.Column('rollback_signature', sa.Text(), nullable=False),
    sa.Column('compatible_export_versions_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('update_id'),
    sa.UniqueConstraint('bundle_hash'),
    sa.UniqueConstraint('manifest_hash')
    )
    op.create_index(op.f('ix_offline_update_packages_deployment_profile_id'), 'offline_update_packages', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_offline_update_packages_state'), 'offline_update_packages', ['state'], unique=False)
    op.create_table('provider_replacement_paths',
    sa.Column('replacement_id', sa.String(length=64), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('service_class', sa.String(length=128), nullable=False),
    sa.Column('export_format', sa.String(length=128), nullable=False),
    sa.Column('adapter_contract', sa.String(length=256), nullable=False),
    sa.Column('replacement_steps_json', sa.JSON(), nullable=False),
    sa.Column('data_exit_json', sa.JSON(), nullable=False),
    sa.Column('limitations_json', sa.JSON(), nullable=False),
    sa.Column('replacement_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('replacement_id'),
    sa.UniqueConstraint('provider_name', 'service_class', name='uq_provider_replacement_path'),
    sa.UniqueConstraint('replacement_hash')
    )
    op.create_index(op.f('ix_provider_replacement_paths_provider_name'), 'provider_replacement_paths', ['provider_name'], unique=False)
    op.create_index(op.f('ix_provider_replacement_paths_service_class'), 'provider_replacement_paths', ['service_class'], unique=False)
    op.create_index(op.f('ix_provider_replacement_paths_state'), 'provider_replacement_paths', ['state'], unique=False)
    op.create_table('autoscaling_policies',
    sa.Column('autoscaling_policy_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('queue_class', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('min_replicas', sa.Integer(), nullable=False),
    sa.Column('max_replicas', sa.Integer(), nullable=False),
    sa.Column('tenant_concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('profile_quotas_json', sa.JSON(), nullable=False),
    sa.Column('global_budget_limit', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('dead_letter_json', sa.JSON(), nullable=False),
    sa.Column('restricted_egress', sa.Boolean(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('autoscaling_policy_id'),
    sa.UniqueConstraint('policy_hash'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'queue_class', 'revision', name='uq_autoscaling_policy_revision')
    )
    op.create_index(op.f('ix_autoscaling_policies_project_id'), 'autoscaling_policies', ['project_id'], unique=False)
    op.create_index(op.f('ix_autoscaling_policies_queue_class'), 'autoscaling_policies', ['queue_class'], unique=False)
    op.create_index(op.f('ix_autoscaling_policies_state'), 'autoscaling_policies', ['state'], unique=False)
    op.create_index(op.f('ix_autoscaling_policies_tenant_id'), 'autoscaling_policies', ['tenant_id'], unique=False)
    op.create_table('edge_nodes',
    sa.Column('edge_node_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('node_identity', sa.String(length=128), nullable=False),
    sa.Column('identity_public_key_hash', sa.String(length=64), nullable=False),
    sa.Column('workload_identity_grant_id', sa.String(length=64), nullable=False),
    sa.Column('software_release', sa.String(length=128), nullable=False),
    sa.Column('software_manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('software_signature', sa.Text(), nullable=False),
    sa.Column('signing_key_id', sa.String(length=128), nullable=False),
    sa.Column('disk_encryption_json', sa.JSON(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('health_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('enrollment_hash', sa.String(length=64), nullable=False),
    sa.Column('enrolled_by', sa.String(length=128), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=128), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('edge_node_id'),
    sa.UniqueConstraint('enrollment_hash'),
    sa.UniqueConstraint('identity_public_key_hash'),
    sa.UniqueConstraint('node_identity'),
    sa.UniqueConstraint('workload_identity_grant_id')
    )
    op.create_index(op.f('ix_edge_nodes_deployment_profile_id'), 'edge_nodes', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_edge_nodes_project_id'), 'edge_nodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_edge_nodes_region'), 'edge_nodes', ['region'], unique=False)
    op.create_index(op.f('ix_edge_nodes_software_manifest_hash'), 'edge_nodes', ['software_manifest_hash'], unique=False)
    op.create_index(op.f('ix_edge_nodes_state'), 'edge_nodes', ['state'], unique=False)
    op.create_index(op.f('ix_edge_nodes_tenant_id'), 'edge_nodes', ['tenant_id'], unique=False)
    op.create_table('edge_update_applications',
    sa.Column('application_id', sa.String(length=64), nullable=False),
    sa.Column('edge_node_id', sa.String(length=64), nullable=False),
    sa.Column('update_id', sa.String(length=64), nullable=False),
    sa.Column('previous_release', sa.String(length=128), nullable=False),
    sa.Column('target_release', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('application_hash', sa.String(length=64), nullable=False),
    sa.Column('applied_by', sa.String(length=128), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_reason', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['edge_node_id'], ['edge_nodes.edge_node_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_id'], ['offline_update_packages.update_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('application_hash'),
    sa.UniqueConstraint('edge_node_id', 'update_id', name='uq_edge_update_application')
    )
    op.create_index(op.f('ix_edge_update_applications_edge_node_id'), 'edge_update_applications', ['edge_node_id'], unique=False)
    op.create_index(op.f('ix_edge_update_applications_state'), 'edge_update_applications', ['state'], unique=False)
    op.create_index(op.f('ix_edge_update_applications_update_id'), 'edge_update_applications', ['update_id'], unique=False)
    op.create_table('hybrid_transfer_policies',
    sa.Column('transfer_policy_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('source_profile_id', sa.String(length=64), nullable=False),
    sa.Column('destination_profile_id', sa.String(length=64), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.String(length=128), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transfer_policy_id'),
    sa.UniqueConstraint('policy_hash'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'revision', name='uq_transfer_policy_revision')
    )
    op.create_index(op.f('ix_hybrid_transfer_policies_destination_profile_id'), 'hybrid_transfer_policies', ['destination_profile_id'], unique=False)
    op.create_index(op.f('ix_hybrid_transfer_policies_project_id'), 'hybrid_transfer_policies', ['project_id'], unique=False)
    op.create_index(op.f('ix_hybrid_transfer_policies_source_profile_id'), 'hybrid_transfer_policies', ['source_profile_id'], unique=False)
    op.create_index(op.f('ix_hybrid_transfer_policies_state'), 'hybrid_transfer_policies', ['state'], unique=False)
    op.create_index(op.f('ix_hybrid_transfer_policies_tenant_id'), 'hybrid_transfer_policies', ['tenant_id'], unique=False)
    op.create_table('project_deployment_bindings',
    sa.Column('binding_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('residency_policy_id', sa.String(length=64), nullable=True),
    sa.Column('transfer_policy_id', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('feature_overrides_json', sa.JSON(), nullable=False),
    sa.Column('cloud_dependencies_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('binding_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployment_profile_id'], ['deployment_profiles.deployment_profile_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('binding_hash'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'revision', name='uq_project_deployment_binding_revision')
    )
    op.create_index(op.f('ix_project_deployment_bindings_deployment_profile_id'), 'project_deployment_bindings', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_project_deployment_bindings_project_id'), 'project_deployment_bindings', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_deployment_bindings_residency_policy_id'), 'project_deployment_bindings', ['residency_policy_id'], unique=False)
    op.create_index(op.f('ix_project_deployment_bindings_state'), 'project_deployment_bindings', ['state'], unique=False)
    op.create_index(op.f('ix_project_deployment_bindings_tenant_id'), 'project_deployment_bindings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_project_deployment_bindings_transfer_policy_id'), 'project_deployment_bindings', ['transfer_policy_id'], unique=False)
    op.create_table('project_deployment_migrations',
    sa.Column('migration_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_profile_id', sa.String(length=64), nullable=False),
    sa.Column('target_profile_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('source_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('source_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('target_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('target_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('validation_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('migration_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('migration_id'),
    sa.UniqueConstraint('migration_hash'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'idempotency_key', name='uq_project_deployment_migration_idempotency')
    )
    op.create_index(op.f('ix_project_deployment_migrations_project_id'), 'project_deployment_migrations', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_deployment_migrations_source_profile_id'), 'project_deployment_migrations', ['source_profile_id'], unique=False)
    op.create_index(op.f('ix_project_deployment_migrations_state'), 'project_deployment_migrations', ['state'], unique=False)
    op.create_index(op.f('ix_project_deployment_migrations_target_profile_id'), 'project_deployment_migrations', ['target_profile_id'], unique=False)
    op.create_index(op.f('ix_project_deployment_migrations_tenant_id'), 'project_deployment_migrations', ['tenant_id'], unique=False)
    op.create_table('residency_policies',
    sa.Column('residency_policy_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('home_region', sa.String(length=64), nullable=False),
    sa.Column('allowed_regions_json', sa.JSON(), nullable=False),
    sa.Column('allowed_modes_json', sa.JSON(), nullable=False),
    sa.Column('asset_rules_json', sa.JSON(), nullable=False),
    sa.Column('worker_rules_json', sa.JSON(), nullable=False),
    sa.Column('provider_rules_json', sa.JSON(), nullable=False),
    sa.Column('default_action', sa.String(length=16), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('residency_policy_id'),
    sa.UniqueConstraint('policy_hash'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'revision', name='uq_residency_policy_revision')
    )
    op.create_index(op.f('ix_residency_policies_project_id'), 'residency_policies', ['project_id'], unique=False)
    op.create_index(op.f('ix_residency_policies_state'), 'residency_policies', ['state'], unique=False)
    op.create_index(op.f('ix_residency_policies_tenant_id'), 'residency_policies', ['tenant_id'], unique=False)


def downgrade() -> None:
    if os.environ.get("SIP_ALLOW_DESTRUCTIVE_DOWNGRADE") != "1":
        raise RuntimeError("destructive downgrade denied; set SIP_ALLOW_DESTRUCTIVE_DOWNGRADE=1 only in an isolated recovery rehearsal")
    required = {
        "SIP_VERIFIED_BACKUP_REFERENCE": os.environ.get("SIP_VERIFIED_BACKUP_REFERENCE", ""),
        "SIP_DOWNGRADE_DRY_RUN_REFERENCE": os.environ.get("SIP_DOWNGRADE_DRY_RUN_REFERENCE", ""),
        "SIP_DOWNGRADE_AUDIT_REFERENCE": os.environ.get("SIP_DOWNGRADE_AUDIT_REFERENCE", ""),
    }
    invalid = [name for name, value in required.items() if re.fullmatch(r"sha256:[0-9a-f]{64}", value) is None]
    rehearsal = os.environ.get("SIP_DOWNGRADE_REHEARSAL_ID", "")
    if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:-]{7,127}", rehearsal) is None:
        invalid.append("SIP_DOWNGRADE_REHEARSAL_ID")
    if invalid:
        raise RuntimeError("destructive downgrade denied; verified backup, dry-run, audit, and rehearsal evidence are required: " + ", ".join(invalid))
    for table in (
        "residency_policies",
        "project_deployment_migrations",
        "project_deployment_bindings",
        "hybrid_transfer_policies",
        "edge_update_applications",
        "edge_nodes",
        "autoscaling_policies",
        "provider_replacement_paths",
        "offline_update_packages",
        "local_upgrade_rehearsals",
        "graceful_shutdown_evidence",
        "deployment_profiles",
        "deployment_drift_reports",
        "deployment_admissions",
        "cdn_derivative_deliveries",
        "aws_environment_manifests",
        "autoscaling_admissions",
    ):
        op.drop_table(table)
