"""Progress 10 recovery retention and deletion"""
from alembic import op
import os
import re
import sqlalchemy as sa
revision = '0020_progress10_recovery_retention'
down_revision = '0019_progress09_deployment_profiles'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_expiry_evidence',
    sa.Column('backup_expiry_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('recovery_point_id', sa.String(length=64), nullable=False),
    sa.Column('resource_scope_json', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('residuals_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('recorded_by', sa.String(length=128), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('backup_expiry_id'),
    sa.UniqueConstraint('evidence_hash')
    )
    op.create_index(op.f('ix_backup_expiry_evidence_project_id'), 'backup_expiry_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_backup_expiry_evidence_recovery_point_id'), 'backup_expiry_evidence', ['recovery_point_id'], unique=False)
    op.create_index(op.f('ix_backup_expiry_evidence_scheduled_for'), 'backup_expiry_evidence', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_backup_expiry_evidence_state'), 'backup_expiry_evidence', ['state'], unique=False)
    op.create_index(op.f('ix_backup_expiry_evidence_tenant_id'), 'backup_expiry_evidence', ['tenant_id'], unique=False)
    op.create_table('deletion_dependency_graphs',
    sa.Column('deletion_graph_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('scope_type', sa.String(length=64), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=False),
    sa.Column('nodes_json', sa.JSON(), nullable=False),
    sa.Column('edges_json', sa.JSON(), nullable=False),
    sa.Column('holds_json', sa.JSON(), nullable=False),
    sa.Column('store_plan_json', sa.JSON(), nullable=False),
    sa.Column('exceptions_json', sa.JSON(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('graph_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('deletion_graph_id'),
    sa.UniqueConstraint('graph_hash')
    )
    op.create_index(op.f('ix_deletion_dependency_graphs_eligible'), 'deletion_dependency_graphs', ['eligible'], unique=False)
    op.create_index(op.f('ix_deletion_dependency_graphs_project_id'), 'deletion_dependency_graphs', ['project_id'], unique=False)
    op.create_index(op.f('ix_deletion_dependency_graphs_scope_id'), 'deletion_dependency_graphs', ['scope_id'], unique=False)
    op.create_index(op.f('ix_deletion_dependency_graphs_scope_type'), 'deletion_dependency_graphs', ['scope_type'], unique=False)
    op.create_index(op.f('ix_deletion_dependency_graphs_state'), 'deletion_dependency_graphs', ['state'], unique=False)
    op.create_index(op.f('ix_deletion_dependency_graphs_tenant_id'), 'deletion_dependency_graphs', ['tenant_id'], unique=False)
    op.create_table('fixity_checks',
    sa.Column('fixity_check_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('expected_sha256', sa.String(length=64), nullable=False),
    sa.Column('observed_sha256', sa.String(length=64), nullable=True),
    sa.Column('replicas_json', sa.JSON(), nullable=False),
    sa.Column('repair_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('check_hash', sa.String(length=64), nullable=False),
    sa.Column('checked_by', sa.String(length=128), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fixity_check_id'),
    sa.UniqueConstraint('check_hash')
    )
    op.create_index(op.f('ix_fixity_checks_project_id'), 'fixity_checks', ['project_id'], unique=False)
    op.create_index(op.f('ix_fixity_checks_resource_id'), 'fixity_checks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_fixity_checks_resource_type'), 'fixity_checks', ['resource_type'], unique=False)
    op.create_index(op.f('ix_fixity_checks_state'), 'fixity_checks', ['state'], unique=False)
    op.create_index(op.f('ix_fixity_checks_tenant_id'), 'fixity_checks', ['tenant_id'], unique=False)
    op.create_table('format_migration_evidence',
    sa.Column('format_migration_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_asset_id', sa.String(length=64), nullable=False),
    sa.Column('derivative_asset_id', sa.String(length=64), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('derivative_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_format', sa.String(length=128), nullable=False),
    sa.Column('target_format', sa.String(length=128), nullable=False),
    sa.Column('migration_tool_json', sa.JSON(), nullable=False),
    sa.Column('validation_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('migration_hash', sa.String(length=64), nullable=False),
    sa.Column('migrated_by', sa.String(length=128), nullable=False),
    sa.Column('migrated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('format_migration_id'),
    sa.UniqueConstraint('migration_hash')
    )
    op.create_index(op.f('ix_format_migration_evidence_derivative_asset_id'), 'format_migration_evidence', ['derivative_asset_id'], unique=False)
    op.create_index(op.f('ix_format_migration_evidence_project_id'), 'format_migration_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_format_migration_evidence_source_asset_id'), 'format_migration_evidence', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_format_migration_evidence_state'), 'format_migration_evidence', ['state'], unique=False)
    op.create_index(op.f('ix_format_migration_evidence_tenant_id'), 'format_migration_evidence', ['tenant_id'], unique=False)
    op.create_table('key_recovery_exercises',
    sa.Column('key_recovery_exercise_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('key_scope_id', sa.String(length=64), nullable=False),
    sa.Column('guardians_json', sa.JSON(), nullable=False),
    sa.Column('approvals_json', sa.JSON(), nullable=False),
    sa.Column('recovery_artifact_reference', sa.String(length=512), nullable=False),
    sa.Column('root_key_exposed', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('exercise_hash', sa.String(length=64), nullable=False),
    sa.Column('exercised_by', sa.String(length=128), nullable=False),
    sa.Column('exercised_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key_recovery_exercise_id'),
    sa.UniqueConstraint('exercise_hash')
    )
    op.create_index(op.f('ix_key_recovery_exercises_key_scope_id'), 'key_recovery_exercises', ['key_scope_id'], unique=False)
    op.create_index(op.f('ix_key_recovery_exercises_project_id'), 'key_recovery_exercises', ['project_id'], unique=False)
    op.create_index(op.f('ix_key_recovery_exercises_state'), 'key_recovery_exercises', ['state'], unique=False)
    op.create_index(op.f('ix_key_recovery_exercises_tenant_id'), 'key_recovery_exercises', ['tenant_id'], unique=False)
    op.create_table('legacy_migration_runs',
    sa.Column('legacy_migration_run_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_release', sa.String(length=64), nullable=False),
    sa.Column('target_release', sa.String(length=64), nullable=False),
    sa.Column('source_backup_id', sa.String(length=64), nullable=False),
    sa.Column('asset_mappings_json', sa.JSON(), nullable=False),
    sa.Column('quarantines_json', sa.JSON(), nullable=False),
    sa.Column('unresolved_anchors_json', sa.JSON(), nullable=False),
    sa.Column('policy_diffs_json', sa.JSON(), nullable=False),
    sa.Column('validation_json', sa.JSON(), nullable=False),
    sa.Column('rollback_evidence_json', sa.JSON(), nullable=False),
    sa.Column('compatibility_report_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('signed_report', sa.Text(), nullable=False),
    sa.Column('migrated_by', sa.String(length=128), nullable=False),
    sa.Column('migrated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('legacy_migration_run_id'),
    sa.UniqueConstraint('report_hash')
    )
    op.create_index(op.f('ix_legacy_migration_runs_project_id'), 'legacy_migration_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_legacy_migration_runs_source_backup_id'), 'legacy_migration_runs', ['source_backup_id'], unique=False)
    op.create_index(op.f('ix_legacy_migration_runs_state'), 'legacy_migration_runs', ['state'], unique=False)
    op.create_index(op.f('ix_legacy_migration_runs_tenant_id'), 'legacy_migration_runs', ['tenant_id'], unique=False)
    op.create_table('purge_runs',
    sa.Column('purge_run_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('deletion_graph_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('store_results_json', sa.JSON(), nullable=False),
    sa.Column('unresolved_exceptions_json', sa.JSON(), nullable=False),
    sa.Column('backup_expiry_json', sa.JSON(), nullable=False),
    sa.Column('cryptographic_erasure_json', sa.JSON(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('executed_by', sa.String(length=128), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('purge_run_id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'idempotency_key', name='uq_purge_run_idempotency')
    )
    op.create_index(op.f('ix_purge_runs_deletion_graph_id'), 'purge_runs', ['deletion_graph_id'], unique=False)
    op.create_index(op.f('ix_purge_runs_evidence_hash'), 'purge_runs', ['evidence_hash'], unique=False)
    op.create_index(op.f('ix_purge_runs_executed_at'), 'purge_runs', ['executed_at'], unique=False)
    op.create_index(op.f('ix_purge_runs_project_id'), 'purge_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_purge_runs_state'), 'purge_runs', ['state'], unique=False)
    op.create_index(op.f('ix_purge_runs_tenant_id'), 'purge_runs', ['tenant_id'], unique=False)
    op.create_table('recovery_game_days',
    sa.Column('recovery_game_day_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('recovery_point_id', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.String(length=128), nullable=False),
    sa.Column('affected_region', sa.String(length=64), nullable=True),
    sa.Column('affected_services_json', sa.JSON(), nullable=False),
    sa.Column('timeline_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('portability_export_json', sa.JSON(), nullable=False),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.Column('evidence_class', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('game_day_hash', sa.String(length=64), nullable=False),
    sa.Column('conducted_by', sa.String(length=128), nullable=False),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('recovery_game_day_id'),
    sa.UniqueConstraint('game_day_hash')
    )
    op.create_index(op.f('ix_recovery_game_days_deployment_profile_id'), 'recovery_game_days', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_recovery_game_days_evidence_class'), 'recovery_game_days', ['evidence_class'], unique=False)
    op.create_index(op.f('ix_recovery_game_days_project_id'), 'recovery_game_days', ['project_id'], unique=False)
    op.create_index(op.f('ix_recovery_game_days_recovery_point_id'), 'recovery_game_days', ['recovery_point_id'], unique=False)
    op.create_index(op.f('ix_recovery_game_days_scenario'), 'recovery_game_days', ['scenario'], unique=False)
    op.create_index(op.f('ix_recovery_game_days_state'), 'recovery_game_days', ['state'], unique=False)
    op.create_index(op.f('ix_recovery_game_days_tenant_id'), 'recovery_game_days', ['tenant_id'], unique=False)
    op.create_table('recovery_locks',
    sa.Column('recovery_lock_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('lock_scope', sa.String(length=128), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('owner_operation_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('recovery_lock_id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'lock_scope', name='uq_recovery_lock_scope')
    )
    op.create_index(op.f('ix_recovery_locks_expires_at'), 'recovery_locks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_recovery_locks_lock_scope'), 'recovery_locks', ['lock_scope'], unique=False)
    op.create_index(op.f('ix_recovery_locks_owner_operation_id'), 'recovery_locks', ['owner_operation_id'], unique=False)
    op.create_index(op.f('ix_recovery_locks_project_id'), 'recovery_locks', ['project_id'], unique=False)
    op.create_index(op.f('ix_recovery_locks_tenant_id'), 'recovery_locks', ['tenant_id'], unique=False)
    op.create_table('recovery_objectives',
    sa.Column('recovery_objective_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('data_class', sa.String(length=128), nullable=False),
    sa.Column('service_class', sa.String(length=128), nullable=False),
    sa.Column('rpo_seconds', sa.Integer(), nullable=False),
    sa.Column('rto_seconds', sa.Integer(), nullable=False),
    sa.Column('degraded_behavior_json', sa.JSON(), nullable=False),
    sa.Column('recovery_method_json', sa.JSON(), nullable=False),
    sa.Column('evidence_class', sa.String(length=64), nullable=False),
    sa.Column('objective_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('recovery_objective_id'),
    sa.UniqueConstraint('objective_hash')
    )
    op.create_index('ix_recovery_objective_scope', 'recovery_objectives', ['tenant_id', 'project_id', 'deployment_profile_id', 'data_class', 'service_class', 'state'], unique=False)
    op.create_index(op.f('ix_recovery_objectives_data_class'), 'recovery_objectives', ['data_class'], unique=False)
    op.create_index(op.f('ix_recovery_objectives_deployment_profile_id'), 'recovery_objectives', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_recovery_objectives_evidence_class'), 'recovery_objectives', ['evidence_class'], unique=False)
    op.create_index(op.f('ix_recovery_objectives_project_id'), 'recovery_objectives', ['project_id'], unique=False)
    op.create_index(op.f('ix_recovery_objectives_service_class'), 'recovery_objectives', ['service_class'], unique=False)
    op.create_index(op.f('ix_recovery_objectives_state'), 'recovery_objectives', ['state'], unique=False)
    op.create_index(op.f('ix_recovery_objectives_tenant_id'), 'recovery_objectives', ['tenant_id'], unique=False)
    op.create_table('recovery_points',
    sa.Column('recovery_point_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('deployment_profile_id', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('evidence_class', sa.String(length=64), nullable=False),
    sa.Column('database_profile', sa.String(length=128), nullable=False),
    sa.Column('package_path', sa.Text(), nullable=False),
    sa.Column('package_sha256', sa.String(length=64), nullable=False),
    sa.Column('package_root_hash', sa.String(length=64), nullable=False),
    sa.Column('database_snapshot_path', sa.Text(), nullable=True),
    sa.Column('database_sha256', sa.String(length=64), nullable=True),
    sa.Column('object_manifest_json', sa.JSON(), nullable=False),
    sa.Column('object_root_hash', sa.String(length=64), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('audit_heads_json', sa.JSON(), nullable=False),
    sa.Column('queue_manifest_json', sa.JSON(), nullable=False),
    sa.Column('key_references_json', sa.JSON(), nullable=False),
    sa.Column('requested_point_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('immutable_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('recovery_point_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('recovery_point_id'),
    sa.UniqueConstraint('recovery_point_hash'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'idempotency_key', name='uq_recovery_point_idempotency')
    )
    op.create_index('ix_recovery_point_scope_time', 'recovery_points', ['tenant_id', 'project_id', 'snapshot_at', 'state'], unique=False)
    op.create_index(op.f('ix_recovery_points_deployment_profile_id'), 'recovery_points', ['deployment_profile_id'], unique=False)
    op.create_index(op.f('ix_recovery_points_evidence_class'), 'recovery_points', ['evidence_class'], unique=False)
    op.create_index(op.f('ix_recovery_points_immutable_until'), 'recovery_points', ['immutable_until'], unique=False)
    op.create_index(op.f('ix_recovery_points_project_id'), 'recovery_points', ['project_id'], unique=False)
    op.create_index(op.f('ix_recovery_points_region'), 'recovery_points', ['region'], unique=False)
    op.create_index(op.f('ix_recovery_points_requested_point_at'), 'recovery_points', ['requested_point_at'], unique=False)
    op.create_index(op.f('ix_recovery_points_snapshot_at'), 'recovery_points', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_recovery_points_state'), 'recovery_points', ['state'], unique=False)
    op.create_index(op.f('ix_recovery_points_tenant_id'), 'recovery_points', ['tenant_id'], unique=False)
    op.create_table('recovery_restore_runs',
    sa.Column('restore_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('recovery_point_id', sa.String(length=64), nullable=False),
    sa.Column('target_tenant_id', sa.String(length=64), nullable=False),
    sa.Column('target_project_id', sa.String(length=64), nullable=False),
    sa.Column('target_region', sa.String(length=64), nullable=False),
    sa.Column('requested_point_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('restore_mode', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('reconciliation_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('writes_reopened', sa.Boolean(), nullable=False),
    sa.Column('rpo_seconds_observed', sa.Integer(), nullable=True),
    sa.Column('rto_seconds_observed', sa.Integer(), nullable=True),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('restore_id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'idempotency_key', name='uq_recovery_restore_idempotency')
    )
    op.create_index(op.f('ix_recovery_restore_runs_project_id'), 'recovery_restore_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_recovery_restore_runs_recovery_point_id'), 'recovery_restore_runs', ['recovery_point_id'], unique=False)
    op.create_index(op.f('ix_recovery_restore_runs_restore_mode'), 'recovery_restore_runs', ['restore_mode'], unique=False)
    op.create_index(op.f('ix_recovery_restore_runs_state'), 'recovery_restore_runs', ['state'], unique=False)
    op.create_index(op.f('ix_recovery_restore_runs_target_project_id'), 'recovery_restore_runs', ['target_project_id'], unique=False)
    op.create_index(op.f('ix_recovery_restore_runs_target_region'), 'recovery_restore_runs', ['target_region'], unique=False)
    op.create_index(op.f('ix_recovery_restore_runs_target_tenant_id'), 'recovery_restore_runs', ['target_tenant_id'], unique=False)
    op.create_index(op.f('ix_recovery_restore_runs_tenant_id'), 'recovery_restore_runs', ['tenant_id'], unique=False)
    op.create_table('retention_assignments',
    sa.Column('retention_assignment_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('retention_class', sa.String(length=64), nullable=False),
    sa.Column('policy_source', sa.Text(), nullable=False),
    sa.Column('hold_status', sa.String(length=32), nullable=False),
    sa.Column('deletion_eligible_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_eligible', sa.Boolean(), nullable=False),
    sa.Column('assignment_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('evaluated_by', sa.String(length=128), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('retention_assignment_id'),
    sa.UniqueConstraint('assignment_hash')
    )
    op.create_index('ix_retention_assignment_resource', 'retention_assignments', ['tenant_id', 'project_id', 'resource_type', 'resource_id', 'state'], unique=False)
    op.create_index(op.f('ix_retention_assignments_deletion_eligible'), 'retention_assignments', ['deletion_eligible'], unique=False)
    op.create_index(op.f('ix_retention_assignments_deletion_eligible_at'), 'retention_assignments', ['deletion_eligible_at'], unique=False)
    op.create_index(op.f('ix_retention_assignments_hold_status'), 'retention_assignments', ['hold_status'], unique=False)
    op.create_index(op.f('ix_retention_assignments_project_id'), 'retention_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_retention_assignments_resource_id'), 'retention_assignments', ['resource_id'], unique=False)
    op.create_index(op.f('ix_retention_assignments_resource_type'), 'retention_assignments', ['resource_type'], unique=False)
    op.create_index(op.f('ix_retention_assignments_retention_class'), 'retention_assignments', ['retention_class'], unique=False)
    op.create_index(op.f('ix_retention_assignments_state'), 'retention_assignments', ['state'], unique=False)
    op.create_index(op.f('ix_retention_assignments_tenant_id'), 'retention_assignments', ['tenant_id'], unique=False)
    op.create_table('tenant_offboarding_runs',
    sa.Column('offboarding_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('export_manifest_json', sa.JSON(), nullable=False),
    sa.Column('retention_report_json', sa.JSON(), nullable=False),
    sa.Column('deletion_report_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('offboarding_hash', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('offboarding_id'),
    sa.UniqueConstraint('offboarding_hash')
    )
    op.create_index(op.f('ix_tenant_offboarding_runs_state'), 'tenant_offboarding_runs', ['state'], unique=False)
    op.create_index(op.f('ix_tenant_offboarding_runs_tenant_id'), 'tenant_offboarding_runs', ['tenant_id'], unique=False)

def downgrade() -> None:
    if os.environ.get("SIP_ALLOW_DESTRUCTIVE_DOWNGRADE") != "1":
        raise RuntimeError("destructive downgrade denied; set SIP_ALLOW_DESTRUCTIVE_DOWNGRADE=1 only in an isolated recovery rehearsal")
    required = {
        "SIP_VERIFIED_BACKUP_REFERENCE": os.environ.get("SIP_VERIFIED_BACKUP_REFERENCE", ""),
        "SIP_DOWNGRADE_DRY_RUN_REFERENCE": os.environ.get("SIP_DOWNGRADE_DRY_RUN_REFERENCE", ""),
        "SIP_DOWNGRADE_AUDIT_REFERENCE": os.environ.get("SIP_DOWNGRADE_AUDIT_REFERENCE", ""),
    }
    invalid = [name for name, value in required.items() if re.fullmatch(r"sha256:[0-9a-f]{64}", value) is None]
    rehearsal = os.environ.get("SIP_DOWNGRADE_REHEARSAL_ID", "")
    if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:-]{7,127}", rehearsal) is None:
        invalid.append("SIP_DOWNGRADE_REHEARSAL_ID")
    if invalid:
        raise RuntimeError("destructive downgrade denied; verified backup, dry-run, audit, and rehearsal evidence are required: " + ", ".join(invalid))
    for table in (
        "tenant_offboarding_runs",
        "retention_assignments",
        "recovery_restore_runs",
        "recovery_points",
        "recovery_objectives",
        "recovery_locks",
        "recovery_game_days",
        "purge_runs",
        "legacy_migration_runs",
        "key_recovery_exercises",
        "format_migration_evidence",
        "fixity_checks",
        "deletion_dependency_graphs",
        "backup_expiry_evidence",
    ):
        op.drop_table(table)
