apiVersion: v1
kind: Service
metadata:
  name: capture-service
  namespace: sip-system
  labels:
    app.kubernetes.io/name: capture-service
    app.kubernetes.io/part-of: spatial-intelligence-platform
    app.kubernetes.io/component: api
    app.kubernetes.io/version: 1.1.0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: capture-service
  ports:
  - name: http
    port: 8080
    targetPort: http
