apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- stateful-dependencies.yaml
images:
- name: ghcr.io/spatial-intelligence-platform/sip-python
  newName: sip/python
  newTag: 1.1.0-local
- name: ghcr.io/spatial-intelligence-platform/sip-web
  newName: sip/web
  newTag: 1.1.0-local
patches:
- path: local-config.patch.yaml
